---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - componentplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - componentplans/finalizers
  verbs:
  - update
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - componentplans/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - components
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - components/finalizers
  verbs:
  - update
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - components/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - portals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - portals/finalizers
  verbs:
  - update
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - portals/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - ratings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - ratings/finalizers
  verbs:
  - update
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - ratings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - repositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - repositories/finalizers
  verbs:
  - update
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - repositories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - repositorys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - repositorys/status
  verbs:
  - get
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - subscriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - subscriptions/finalizers
  verbs:
  - update
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - subscriptions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - pipelines
  - taskruns
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns/finalizers
  - pipelines/finalizers
  - taskruns/finalizers
  - tasks/finalizers
  verbs:
  - update
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns/status
  - pipelines/status
  - taskruns/status
  - tasks/status
  verbs:
  - get
  - patch
  - update
