apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: ComponentPlan
metadata:
  name: do-once-wordpress-sample-16.1.12
  namespace: default
spec:
  approved: true
  component:
    name: repository-bitnami-sample.wordpress
    namespace: kubebb-system
  name: my-wordpress
  override: {}
  repository:
    name: repository-bitnami-sample
    namespace: kubebb-system
  version: 16.1.12
#status:
#  conditions:
#    - lastTransitionTime: "2023-06-13T07:09:42Z"
#      reason: ""
#      status: "True"
#      type: Approved
#    - lastTransitionTime: "2023-06-13T07:09:48Z"
#      reason: ""
#      status: "True"
#      type: Installed
#    - lastTransitionTime: "2023-06-13T07:09:48Z"
#      reason: ""
#      status: "True"
#      type: Succeeded
#  images:
#    - docker.io/bitnami/mariadb:10.11.3-debian-11-r5
#    - docker.io/bitnami/wordpress:6.2.2-debian-11-r9
#  resources:
#    - apiVersion: v1
#      kind: ServiceAccount
#      name: my-wordpress-mariadb
#      specDiffwithExist: no spec diff, but some field like resourceVersion will update
#    - apiVersion: v1
#      kind: Secret
#      name: my-wordpress-mariadb
#      specDiffwithExist: |
#        data:
#          mariadb-password: VDQxVWl4ZG9NNA== -> OURBcVNCVTJVTg==
#          mariadb-root-password: TklYdmtVTGF3bw== -> M3BSbGtYb01vUQ==
#    - apiVersion: v1
#      kind: Secret
#      name: my-wordpress
#      specDiffwithExist: |
#        data:
#          wordpress-password: MEkzWHlXaThRTQ== -> WW53czgxTEIyYQ==
#    - apiVersion: v1
#      kind: ConfigMap
#      name: my-wordpress-mariadb
#      specDiffwithExist: no spec diff, but some field like resourceVersion will update
#    - apiVersion: v1
#      kind: PersistentVolumeClaim
#      name: my-wordpress
#      specDiffwithExist: diff with exist
#    - apiVersion: v1
#      kind: Service
#      name: my-wordpress-mariadb
#      specDiffwithExist: no spec diff, but some field like resourceVersion will update
#    - apiVersion: v1
#      kind: Service
#      name: my-wordpress
#      specDiffwithExist: no spec diff, but some field like resourceVersion will update
#    - apiVersion: apps/v1
#      kind: Deployment
#      name: my-wordpress
#      specDiffwithExist: |
#        metadata:
#          annotations: map[deployment.kubernetes.io/revision:2] -> <empty> (REMOVED)
#        spec:
#          replicas: 3 -> 1
#          template:
#            spec:
#              containers:
#                '[#0]':
#                  image: docker.io/bitnami/wordpress:6.2.2-debian-11-r9 -> docker.io/bitnami/wordpress:6.2.2-debian-11-r11
#                  resources:
#                    requests:
#                      cpu: 400m -> 300m
#                      memory: 1Gi -> 512Mi
#    - apiVersion: apps/v1
#      kind: StatefulSet
#      name: my-wordpress-mariadb
#      specDiffwithExist: |
#        spec:
#          template:
#            metadata:
#              annotations:
#                checksum/configuration: 5ebfa426b5e0d78c7249bd5acac22f0e8e36f367b9ba096cb685abc7598f2ae0
#                  -> abcc3b0ea604fd8129236d8ab6bd4552c963cad6ef0dce866d30be131c6196e5
#            spec:
#              containers:
#                '[#0]':
#                  image: docker.io/bitnami/mariadb:10.11.3-debian-11-r5 -> docker.io/bitnami/mariadb:10.11.4-debian-11-r0
