apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: component-security
  namespace: kubebb-system
  annotations:
    tekton.dev/tags: component-security
    tekton.dev/displayName: component-security
    tekton.dev/platforms: linux/amd64
    core.kubebb.k8s.com.cn/dimension: security
spec:
  description: >-
    security checks on component
  params:
    - name: COMPONENT_NAME
      description: >-
        component name
    - name: REPOSITORY_NAME
      description: repository name
      default: "kubebb"
    - name: VERSION
      description: component version
    - name: URL
      description: the full URL of the component tgz file.
  results:
    - name: RBACCM
      value: $(tasks.security-rbac.results.RBACCM)
  tasks:
    - name: security-rbac
      retries: 2
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: security-rbac
          - name: namespace
            value: kubebb-system
      params:
        - name: url
          value: $(params.URL)
        - name: component
          value: $(params.COMPONENT_NAME)
        - name: version
          value: $(params.VERSION)
        - name: repository
          value: $(params.REPOSITORY_NAME)
